In [2]:
import numpy as np 
import sys 

In [3]:
a = np.array([1,2,3]) 
print(a)

[1 2 3]


In [4]:
b = np.array([[1,2,3] , [2,3,4]]) 
print(b) 

[[1 2 3]
 [2 3 4]]


In [5]:
a.ndim 

1

In [6]:
a.shape 

(3,)

In [7]:
b.shape 

(2, 3)

In [8]:
zeros = np.zeros((2,3)) 
print(zeros) 

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
lspace = np.linspace(1,5,12) 
print(lspace) 

[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]


In [10]:
emp = np.empty((4,6))  
print(emp) 

[[ 6.95261690e-310  6.95256872e-310  0.00000000e+000  2.03711596e-312
   9.99940259e-312  4.94065646e-324]
 [ 0.00000000e+000  0.00000000e+000  4.04738577e-320  0.00000000e+000
   1.23022346e-321  9.99973467e-312]
 [-3.42843178e+186  0.00000000e+000  0.00000000e+000  9.99973469e-312
   3.06320700e-322  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   4.94065646e-324              nan]]


**created an empty array with elements of lspace** 

In [11]:
emp_like = np.empty_like(lspace) 
print(emp_like) 

[6.95261690e-310 6.95256872e-310 2.03711596e-312 9.99940259e-312
 4.94065646e-324 4.04738577e-320 1.23022346e-321 9.99973467e-312
 3.42843178e+186 9.99973469e-312 3.06320700e-322 4.94065646e-324]


In [12]:
ide = np.identity(45) 
print(ide) 

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [13]:
arr = np.arange(99) # creates an array from 0 to 98 with 99 elements 
print(arr) 


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [14]:
arr = arr.reshape(3 ,33 ) 
print(arr) 

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]


In [15]:
arr = arr.ravel()
print(arr) 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [16]:
x = np.array([[1,2,3] , [4,5,6] , [7,0,1]]) 
print(x) 

[[1 2 3]
 [4 5 6]
 [7 0 1]]


In [17]:
print(x.sum(axis = 0)) 

[12  7 10]


In [18]:
print(x.sum(axis = 1)) 


[ 6 15  8]


In [19]:
print(x.T) 

[[1 4 7]
 [2 5 0]
 [3 6 1]]


In [20]:
print(x.T) 

[[1 4 7]
 [2 5 0]
 [3 6 1]]


In [21]:
x.flat 

In [22]:
for item in x.flat : # this flat thing gives you a flat array out of an dimensional array 
    print(item) 

1
2
3
4
5
6
7
0
1


In [23]:
print(x.flat) 

In [24]:
one = np.array( [1,3,4,643,2]) 
print(one) 

[  1   3   4 643   2]


In [25]:
one.argmax()  # gives you index for the max element and min with argmin 

3

In [26]:
one.argmin() 

0

In [27]:
one = np.array([[1,2,3] , [4,5,6] , [7,0,1] ]) 
print(one) 

[[1 2 3]
 [4 5 6]
 [7 0 1]]


In [28]:
print(one.argmax(axis = 1 )) 

[2 2 0]


In [29]:
print(one.argmin(axis = 0)) 

[0 2 2]


In [30]:
print(np.where(one > 5) )


(array([1, 2], dtype=int64), array([2, 0], dtype=int64))


In [31]:
arr = [1,2,3] 
nu_arr = np.array([1,2,3]) 

print(nu_arr.itemsize * nu_arr.size  )
print( sys.getsizeof(1) * len(arr) ) 

12
84


In [32]:
arr = np.array([[1,2,3,4,5,6] , [7,8,9,10,11,12]] )  
print(arr) 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [33]:
arr[ 1 , 2 ] 

9

In [34]:
arr[0 , :] 

array([1, 2, 3, 4, 5, 6])

In [35]:
arr[ :  , 1 ] 

array([2, 8])

In [36]:
print(arr[: , 2 : 5 ]) 

[[ 3  4  5]
 [ 9 10 11]]


In [37]:
print(arr[0 , :]) 

[1 2 3 4 5 6]


In [38]:
print(arr[ 0 , 1 : 6 : 2]) 


[2 4 6]


In [39]:
arr[ 0 , 0 : 5 : 2 ] 

array([1, 3, 5])

In [40]:
print(arr[ : , 2:6:2 ])

[[ 3  5]
 [ 9 11]]


In [41]:
print(arr[ : , 1: 6:2] ) 

[[ 2  4  6]
 [ 8 10 12]]


In [42]:
arr = np.array([ [[1,2] , [3,4]]  , [[5,6],[7,8]] ])  
print(arr) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [43]:
print(arr[0,1,1]) 

4


In [67]:
zeros = np.zeros((4 , 2 ,2)) 
print(zeros) 

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [45]:
print(np.ones((4,2,2) , dtype = 'int32')) 

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [69]:
np.full(b.shape , 4) 

array([4, 4, 4])

In [47]:
np.full_like( b , 4 )

array([[4, 4, 4],
       [4, 4, 4]])

In [48]:
np.random.randint( 7 , size = (3,3)) #  np.random.randint( low , high , size ) so here low -> high -1 is the region and low default is 0 

array([[3, 3, 4],
       [2, 5, 2],
       [5, 4, 5]])

In [72]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
arr = np.array([[1,2,3]]) 
r1 = np.repeat( arr , 3 , axis = 0 ) 
print(r1) 

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [70]:
r2 = np.repeat( arr , 3 , axis = 1 ) 
print(r2) 

[[1 1 1 2 2 2 3 3 3]]


In [60]:
output = np.ones((5,5)) 
print(output) 

z = np.zeros((3,3)) 
print(z) 

z[1,1] = 9 
print(z) 

output[1:-1 , 1:-1] = z 
print(output) 



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [66]:
# BE CAREFUL WHILE COPYING ELEMENTS 
a = np.array([1,2,3]) 
b = a.copy() 
b[0] = 100 
print(b)  
print(a) 

[100   2   3]
[1 2 3]


In [75]:
a = np.ones((2,3)) 

b = np.full((3,2) , 2) 

np.matmul(a,b) 

array([[6., 6.],
       [6., 6.]])

In [76]:
c = np.identity(3)  
np.linalg.det(c) 

1.0

In [77]:
stats = np.array([[1,2,3] , [4,5,6]]) 
print(stats) 

[[1 2 3]
 [4 5 6]]


In [78]:
stats.min() 

1

In [79]:
stats.max()  # this gives the value of that element 

6

In [80]:
stats.argmax() # argmax gives you the index for the maximum element 

5

In [81]:
np.max(stats) 

6

In [84]:
np.max(stats , axis = 0) # max on each row / col 

array([4, 5, 6])

In [85]:
np.sum( stats )

21

In [86]:
np.sum(stats , axis = 1) 

array([ 6, 15])

In [95]:
before = np.array([[1,2,3,4] , [5,6,7,8]]) 
print(before) 

print("\n")

after = before.reshape((2 , 2,2))
print(after) 

[[1 2 3 4]
 [5 6 7 8]]


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [96]:
#vertically stacking vectors 

v1 = np.array([1,2,3,4]) 
v2 = np.array([4,5,6,7]) 

np.vstack([v1 , v2])  # v1 , v2 , v1 , v2 yeh bhi chal jayega bhai 

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [98]:
h1 = np.ones(2) 
h2 = np.zeros(3) 

np.hstack([h1 , h2]) 

array([1., 1., 0., 0., 0.])

In [112]:
filedata = np.genfromtxt(r"C:\code\23JAVA\data1.txt" , delimiter = "," ) ;
newdata = filedata.astype('int32') 
print(newdata) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [115]:
filedata < 5

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [117]:
filedata[filedata < 10] 

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])